language: node_js
node_js:
  - stable
before_install:
  - sudo add-apt-repository ppa:ondrej/php5-5.6 -y
  - sudo apt-get update
  - sudo apt-get install php5 -y
install:
  - npm install gulp -g
  - npm install
script: gulp
